config/routes.rb
Scheduler::Application.routes.draw do
  devise_for :users

  root :to => 'appointments#index'

  resources :instructors

  resources :appointments

end

app/models/appointment.rb
class Appointment < ActiveRecord::Base
  attr_accessible :duration, :instructor_id, :start_time
  belongs_to :instructor
  has_one :specialty

  def end_time
    start_time + duration.minutes
  end


end

app/models/appointment_type.rb
class AppointmentType < ActiveRecord::Base

  has_many :specialties

end

app/models/instructor.rb
class Instructor < ActiveRecord::Base
  attr_accessible :bio, :name, :specialties

  has_many :appointments
  has_many :specialties
end

app/models/specialty.rb
class Specialty < ActiveRecord::Base

  belongs_to :appointment_type

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  before_filter :authenticate_user!
  
end

app/controllers/appointments_controller.rb
class AppointmentsController < ApplicationController

  def index
    @appointments = Appointment.all
    @instructors = Instructor.scoped.includes(:appointments)
  end

  def show
    @appointment = Appointment.find(params[:id])
  end

  def create
    @appointment = Appointment.new(params[:appointment])
    if @appointment.save
      respond_to do |format|
        format.html {flash[:notice] = 'Appointment succesfully created'
            redirect_to appointments_path}
        format.json
      end
    else
      redirect_to new_appointment_path
    end
  end

  def new
    @appointment = Appointment.new
      respond_to do |format|
        format.html
        format.json {render json: @appointment}
      end
  end

  def destroy
    @appointment = Appointment.find(params[:id])
    @appintment.destroy
      respond_to do |format|
        format.html {flash[:notice] = "Successfully Deleted"}
        format.js
      end
  end
end

app/controllers/instructors_controller.rb
class InstructorsController < ApplicationController
  def index
    @instructors = Instructor.all
  end

  def show
    @instructor = Instructor.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @instructor }
    end
  end

  def new
    @instructor = Instructor.new
      respond_to do |format|
        format.html
        format.js {render json: instructor}
      end
  end

  def create
     @instructor = Instructor.new(params[:instructor])

     respond_to do |format|
       if @instructor.save
         format.html { redirect_to @instructor, notice: 'Instructor was successfully created.' }
         format.json { render json: @instructor, status: :created, location: @instructor }
       else
         format.html { render action: "new" }
         format.json { render json: @instructor.errors, status: :unprocessable_entity }
       end
     end
   end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/appointments_helper.rb
module AppointmentsHelper
  def duration_array
    first_array = [15]
      11.times do
        n = first_array.last + 15
        first_array << n
      end
    return first_array
  end

  def convert_mins_to_hours
    duration_array.collect do |mins|
      if mins/60 == 0
        label = mins.to_s + ' minutes'
      elsif mins % 60 == 0
        label = (mins/60).to_s + " hours"
      elsif mins % 60 != 0
        label = (mins/60).to_s + " hour " + (mins % 60).to_s + " minutes"
      end
      [label, mins]
    end
  end

  def time_array
    t = Time.now
    first_appt = Time.new t.year, t.month, t.day, 7
    full_time_array = [first_appt]
    55.times do
      full_time_array << full_time_array.last + 15.minutes
    end
    full_time_array
  end
end

app/helpers/instructors_helper.rb
module InstructorsHelper
end

app/views/Appointments/_form.html.erb
<%= form_for(@appointment) do |f| %>
  <% if @appointment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@appointment.errors.count, "error") %> prohibited this appointment from being saved:</h2>

      <ul>
      <% @appointment.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :instructor %><br />
    <%= f.collection_select(:instructor_id, Instructor.all, :id, :name) %>
  </div>

  <div class="field">
    <%= f.label :start_time %><br />
    <%= f.text_field :start_time, :id => 'startTime' %>
  </div>

  <div class="field">
    <%= f.label :duration %><br />
    <%= f.select :duration, convert_mins_to_hours %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>

<% end %>

app/views/Appointments/index.html.erb
<h1>Listing appointments</h1>

<table>
  <tr>
    <th>Instructor</th>
    <th>Start time</th>
    <th>End time</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

  <% @appointments.each do |appointment| %>
    <tr>
      <td><%= appointment.instructor.name %></td>
      <td><%= appointment.start_time %></td>
      <td><%= appointment.end_time %></td>
      <td><%= link_to 'Show', appointment %></td>
      <td><%= link_to 'Edit', edit_appointment_path(appointment) %></td>
      <td><%= link_to 'Destroy', appointment, method: :delete, data: {confirm: 'Are you sure?'} %></td>
    </tr>
  <% end %>
</table>

<br/>

<table>
  <tr>
    <th>Times</th>
    <% @instructors.each do |instructor| %>
      <th><%= instructor.name %></th>
    <% end %>
  </tr>

  <% time_array.each do |time| %>
    <tr>
      <td><%= "#{time.strftime('%l:%M %P')}"%> </td>
      <% @instructors.each do |instructor| %>
        <%# instructor.appointments.first.try(:start_time) %>
        <td>is this reserved for <%= instructor.name %>?</td>
      <% end %>
    </tr>
  <% end %>
</table>

<%= link_to 'New Appointment', new_appointment_path %>

app/views/Appointments/new.html.erb
<h1>Make a New appointment</h1>

<%= render 'form' %>

<%= link_to 'Back', appointments_path %>

app/views/instructors/_form.html.erb
<%= form_for(@instructor) do |f| %>
  <% if @instructor.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@instructor.errors.count, "error") %> prohibited this instructor from being saved:</h2>

      <ul>
      <% @instructor.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>


  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :bio %><br />
    <%= f.text_field :bio %>
  </div>
  <div class="field">
    <%= f.label :specialties %><br />
    <%= f.text_field :specialties %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/instructors/index.html.erb
<h1>Listing instructors</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Bio</th>
    <th>Specialties</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @instructors.each do |instructor| %>
  <tr>
    <td><%= instructor.name %></td>
    <td><%= instructor.bio %></td>
    <td><%= instructor.specialties %></td>
    <td><%= link_to 'Show', instructor %></td>
    <td><%= link_to 'Edit', edit_instructor_path(instructor) %></td>
    <td><%= link_to 'Destroy', instructor, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Instructor', new_instructor_path %>

app/views/instructors/new.html.haml
%h1 New instructor

= render 'form'

= link_to 'Back', instructors_path

app/views/instructors/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @instructor.name %>
</p>

<p>
  <b>Bio:</b>
  <%= @instructor.bio %>
</p>

<p>
  <b>Specialties:</b>
  <%= @instructor.specialties %>
</p>


<%= link_to 'Edit', edit_instructor_path(@instructor) %> |
<%= link_to 'Back', instructors_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Scheduler</title>
  <%= stylesheet_link_tag "application", :media => "all" %>
  <%= stylesheet_link_tag "application" %>
  <%= stylesheet_link_tag "http://ajax.googleapis.com/ajax/libs/jqueryui/1.8.16/themes/base/jquery-ui.css" %>
  <%= javascript_include_tag "application", "appointments" %>
  <%= csrf_meta_tags %>
</head>
<body>

  <% if user_signed_in? %>
    Hello <%= current_user.email %>!
  <%= link_to "Sign out", destroy_user_session_path, :method => :delete %>
  <% end %>

  <p class="notice"><%= notice %></p>
  <p class="alert"><%= alert %></p>

<%= yield %>

</body>
</html>